image_finetune: False

output_dir: "outputs_pose16"
pretrained_model_path: "../data/pretrained_models/RV/rv-5-1"
pretrained_clip_path: "../data/pretrained_models/DINO/dinov2"
pretrained_mm_path: "../data/pretrained_models/MM/animatediff/mm_sd_v15_v2.ckpt"

unet_additional_kwargs:
  use_motion_module              : True
  motion_module_resolutions      : [ 1,2,4,8 ]
  unet_use_cross_frame_attention : False
  unet_use_temporal_attention    : False

  motion_module_type: Vanilla
  motion_module_kwargs:
    num_attention_heads                : 8
    num_transformer_block              : 1
    attention_block_types              : [ "Temporal_Self", "Temporal_Self" ]
    temporal_position_encoding         : True
    temporal_position_encoding_max_len : 32
    temporal_attention_dim_div         : 1
    zero_initialize                    : True

pose_guider_kwargs:
  pose_guider_type:     "side_guider"
  args:
    out_channels:       [ 320, 320, 640, 1280, 1280 ]

clip_projector_kwargs:
  projector_type:        "ff"
  in_features:           1024
  out_features:          768

zero_snr:                True
v_pred:                  True
train_cfg:               False
snr_gamma:               5.0
fix_ref_t:               True
pose_shuffle_ratio:      0.05

vae_slicing:             True
fps:                     8

validation_kwargs:
  guidance_scale:        2

train_data:
  - dataset:
      dataset_class: VideoDataset
      args:
        root_dir: "../data/data/"
        split: "train"
        sample_size: [ 768, 576 ]
        clip_size: [ 320, 240 ]
        image_finetune: False
        ref_mode: "random"
        keypoints_type: "MP"
        sample_n_frames: 30

validation_data:
  # dataset_class: VideoDataset
  # args:
  #   root_dir: "/opt/dlami/nvme/data/"
  #   split: "train"
  #   sample_size: [ 768, 576 ]
  #   clip_size: [ 320, 240 ]
  #   image_finetune: False
  #   ref_mode: "first"
  #   keypoints_type: "MP"
  #   sample_n_frames: 16

  # dataset_class: FolderDataset
  # args:
  #   video_dir: "../data/data/val/sign_kpt_data_MP/"
  #   sample_size: [ 768, 576 ]
  #   clip_size: [ 320, 240 ]
  #   image_finetune: False
  #   ref_mode: "first"
  #   keypoints_type: "MP"
  #   sample_n_frames: 56
  #   start_index: 0
  #   fix_gap: False

  dataset_class: FolderDataset
  args:
    video_dir: "../data/data/test/sign_kpt_data_MP/"
    sample_size: [ 768, 576 ]
    clip_size: [ 320, 240 ]
    image_finetune: False
    ref_mode: "first"
    keypoints_type: "MP" # "MP" or "DW"
    sample_n_frames: 56
    start_index: 0
    fix_gap: False

trainable_modules:
  - "motion_modules."

unet_checkpoint_path: "/home/ubuntu/realisDance_generation/outputs_text/stage1_hamer-2025-04-08T04/checkpoints/checkpoint-final.ckpt"

lr_scheduler:     "constant_with_warmup"
learning_rate:    1e-5
lr_warmup_steps:  5000
train_batch_size: 1
validation_batch_size: 1

max_train_epoch:      -1
max_train_steps:      160000
checkpointing_epochs: -1
checkpointing_steps:  10000
checkpointing_steps_tuple:  [ 2, 5000 ]

global_seed: 42
mixed_precision: "fp16"

is_debug: False
